-- Create categories table
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Allow everyone to read categories
CREATE POLICY "Categories are viewable by everyone" ON public.categories
  FOR SELECT USING (TRUE);

-- Allow only admins to modify categories
CREATE POLICY "Categories are insertable/updatable/deletable by admins" ON public.categories
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Insert initial categories from the hardcoded list
INSERT INTO public.categories (name) VALUES
('Smart watch'),
('Buds'),
('Buds plus'),
('SPEAKERS'),
('Air tag'),
('Watch strap')
ON CONFLICT (name) DO NOTHING;
