-- Lot 4: real-time support chat. Run in the Supabase SQL Editor.
--
-- One conversation per customer: conversation_id == the customer's auth uid.
-- Customer messages: sender_id = customer, conversation_id = customer.
-- Admin replies:      sender_id = admin,    conversation_id = target customer.
CREATE TABLE public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL CHECK (char_length(content) BETWEEN 1 AND 4000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  read_at TIMESTAMPTZ
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- SELECT: a customer sees only their own conversation; an admin sees all.
CREATE POLICY "Read own conversation or admin reads all" ON public.messages
  FOR SELECT TO authenticated
  USING (conversation_id = (select auth.uid()) OR public.is_admin());

-- INSERT: the sender must be the current user. A customer may only post into
-- their own conversation; an admin may post into any conversation.
CREATE POLICY "Send message" ON public.messages
  FOR INSERT TO authenticated
  WITH CHECK (
    sender_id = (select auth.uid())
    AND (
      conversation_id = (select auth.uid())
      OR public.is_admin()
    )
  );

-- No UPDATE/DELETE policies on purpose: read receipts are set via the
-- SECURITY DEFINER mark_messages_read() RPC below, so clients cannot tamper
-- with message rows directly.

CREATE INDEX idx_messages_conversation_created
  ON public.messages (conversation_id, created_at);
CREATE INDEX idx_messages_unread
  ON public.messages (conversation_id) WHERE read_at IS NULL;
CREATE INDEX idx_messages_sender ON public.messages (sender_id);

-- Live updates via Supabase Realtime (no polling).
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;

-- Mark all inbound (not-sent-by-caller) messages in a conversation as read.
CREATE OR REPLACE FUNCTION public.mark_messages_read(p_conversation UUID)
RETURNS VOID AS $$
BEGIN
  IF (select auth.uid()) IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;
  IF NOT (p_conversation = (select auth.uid()) OR public.is_admin()) THEN
    RAISE EXCEPTION 'not authorized';
  END IF;
  UPDATE public.messages
     SET read_at = NOW()
   WHERE conversation_id = p_conversation
     AND sender_id <> (select auth.uid())
     AND read_at IS NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.mark_messages_read(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mark_messages_read(UUID) TO authenticated;
