-- Run this script in the Supabase SQL Editor

-- 1. Create a custom users profile table (linked to auth.users)
CREATE TABLE public.user_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  full_name TEXT,
  phone TEXT,
  role TEXT DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Turn on Row Level Security
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- Allow users to read their own profile
CREATE POLICY "Users can view own profile" ON public.user_profiles
  FOR SELECT USING (auth.uid() = id);

-- Function to check if user is admin (avoids recursion)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (
    SELECT role = 'admin'
    FROM public.user_profiles
    WHERE id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Allow admins to read all profiles
CREATE POLICY "Admins can view all profiles" ON public.user_profiles
  FOR SELECT USING (public.is_admin());

-- Function to handle new user registration
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_profiles (id, email, full_name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function when a new user signs up
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 2. Create products table
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  image TEXT,
  images TEXT[] DEFAULT '{}',
  colors TEXT[] DEFAULT '{}',
  sizes TEXT[] DEFAULT '{}',
  features JSONB DEFAULT '{}',
  category_id INT,
  category TEXT,
  is_featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: Anyone can read products. Only admins can modify.
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Products are viewable by everyone" ON public.products
  FOR SELECT USING (TRUE);

CREATE POLICY "Products are insertable/updatable/deletable by admins" ON public.products
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role = 'admin'
    )
  );


-- 3. Create orders table
CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  total_amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'Pending',
  name TEXT,
  phone TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: Users can see their own orders. Admins can see/update all.
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own orders" ON public.orders
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own orders" ON public.orders
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can view all orders" ON public.orders
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role = 'admin'
    )
  );
  
CREATE POLICY "Admins can update all orders" ON public.orders
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role = 'admin'
    )
  );


-- 4. Create order_items table
CREATE TABLE public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id),
  quantity INT NOT NULL,
  price_at_time DECIMAL(10,2) NOT NULL
);

-- RLS: Users can see items of their own orders. Admins can see all.
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own order items" ON public.order_items
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.orders WHERE id = order_items.order_id AND user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own order items" ON public.order_items
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.orders WHERE id = order_items.order_id AND user_id = auth.uid()
    )
  );

CREATE POLICY "Admins can view all order items" ON public.order_items
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Insert dummy smart watch products
INSERT INTO public.products (name, brand, model, description, price, image, images, colors, sizes, features, category_id, category, is_featured)
VALUES 
('Apple Watch Series 9', 'Apple', 'Series 9', 'Advanced health features, ECG, blood oxygen monitoring. Always-on Retina display.', 399.00, 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400', ARRAY['https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400'], ARRAY['Midnight', 'Starlight', 'Silver', 'Red'], ARRAY['41mm', '45mm'], '{"battery": "18h", "waterproof": "IPX8", "bluetooth": "5.3", "gps": true}'::jsonb, 1, 'Sport', true),
('Samsung Galaxy Watch 6', 'Samsung', 'Galaxy Watch 6', 'Comprehensive health tracking, sleep analysis, fitness monitoring with GPS.', 349.99, 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400', ARRAY['https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400'], ARRAY['Black', 'Silver', 'Gold'], ARRAY['44mm', '40mm'], '{"battery": "40h", "waterproof": "5ATM", "bluetooth": "5.3", "gps": true}'::jsonb, 1, 'Sport', true),
('Garmin Fenix 7', 'Garmin', 'Fenix 7', 'Premium multisport GPS watch with solar charging and advanced training features.', 699.99, 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400', ARRAY['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400'], ARRAY['Black', 'Carbon Gray', 'Slate Blue'], ARRAY['47mm', '42mm'], '{"battery": "18 days", "waterproof": "10ATM", "bluetooth": "5.0", "gps": true, "solar": true}'::jsonb, 1, 'Sport', true);
